apiVersion: v1
kind: Service
metadata:
  name: hello-devops
  labels:
    app: hello-devops
spec:
  type: NodePort
  selector:
    app: hello-devops
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30080
